[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "objectViewer"
version = "0.1.0"
description = "Object detection and visualization library"
dependencies = [
    "opencv-python",
    "numpy",
    "ultralytics"
]

[tool.setuptools]
packages = ["objectViewer"]
